accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import profile

urlpatterns = (
    path('', include('django.contrib.auth.urls')),
    path('profile/', profile, name='profile'),
)

teams/urls.py
from django.urls import path, include
from . import views

app_name = 'teams'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('<slug:team_slug>/', views.view, name='view'),
    path('<slug:team_slug>/invite/', views.invite, name='invite'),
    path('<slug:team_slug>/lunches/', include('lunches.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UserForm
from django.contrib.auth.models import User
from teams.models import TeamMember, Team


# Create your views here.
@login_required
def profile(request):
    if request.method == 'POST':
        print(request.POST)
        form = UserForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
    form = UserForm(instance=request.user)
    teams = request.user.organizations_organization.all()
    return render(request, 'accounts/profile.html', {'form': form, 'teams': teams})

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% block content %}
    <h1>Welcome {{ user }}</h1>
    <div class="row">
      <div class="col-lg-6 text-left">
        <h2>Update Settings</h2>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
      </div>
      <div class="col-lg-6 text-left">
        <h2>My Teams</h2>
        <ul class="list-group">
            {% for team in teams %}
                <li class="list-group-item"><a href="{% url 'teams:view' team.slug %}">{{ team.name }}</a></li>
            {% endfor %}
        </ul>
        <a class="btn btn-primary" href="{% url 'teams:create' %}">New Team</a>
      </div>
    </div>      
{% endblock %}