teams/urls.py
from django.urls import path, include
from . import views

app_name = 'teams'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('<slug:team_slug>/', views.view, name='view'),
    path('<slug:team_slug>/invite/', views.invite, name='invite'),
    path('<slug:team_slug>/lunches/', include('lunches.urls')),
]

teams/models.py
from django.db import models
from organizations.models import Organization, OrganizationUser

class Team(Organization):
    class Meta:
        proxy = True

class TeamMember(OrganizationUser):
    class Meta:
        proxy = True

teams/forms.py
from django import forms
from django.conf import settings
from django.contrib.sites.models import Site
from django.contrib.auth import get_user_model
from organizations.backends import invitation_backend
from .models import TeamMember, Team

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ('name', )

class TeamMemberAdminForm(forms.ModelForm):
    """
    Form class for editing OrganizationMembers *and* the linked user model.
    """
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField()

    class Meta:
        exclude = ('user', 'is_admin')
        model = TeamMember

    def __init__(self, *args, **kwargs):
        super(TeamMemberAdminForm, self).__init__(*args, **kwargs)
        if self.instance.pk is not None:
            self.fields['first_name'].initial = self.instance.user.first_name
            self.fields['last_name'].initial = self.instance.user.last_name
            self.fields['email'].initial = self.instance.user.email

    def save(self, *args, **kwargs):
        """
        This method saves changes to the linked user model.
        """
        if self.instance.pk is None:
            site = Site.objects.get(pk=settings.SITE_ID)
            self.instance.user = invitation_backend().invite_by_email(
                    self.cleaned_data['email'],
                    **{'first_name': self.cleaned_data['first_name'],
                        'last_name': self.cleaned_data['last_name'],
                        'organization': self.cleaned_data['organization'],
                        'domain': site})
        self.instance.user.first_name = self.cleaned_data['first_name']
        self.instance.user.last_name = self.cleaned_data['last_name']
        self.instance.user.email = self.cleaned_data['email']
        self.instance.user.save()
        return super(TeamMemberForm, self).save(*args, **kwargs)

class TeamMemberForm(forms.ModelForm):
    """
    Form class for editing OrganizationMembers *and* the linked user model.
    """
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField()

    class Meta:
        exclude = ('user', 'organization')
        model = TeamMember

    def __init__(self, *args, **kwargs):
        super(TeamMemberForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        """
        This method saves changes to the linked user model.
        """
        # Hack in the organization field since we excluded it manually
        self.instance.organization = kwargs.pop('team')
        if self.instance.pk is None:
            site = Site.objects.get(pk=settings.SITE_ID)
            self.instance.user = invitation_backend().invite_by_email(
                    self.cleaned_data['email'],
                    **{'first_name': self.cleaned_data['first_name'],
                        'last_name': self.cleaned_data['last_name'],
                        'organization': self.instance.organization,
                        'domain': site})
        self.instance.user.first_name = self.cleaned_data['first_name']
        self.instance.user.last_name = self.cleaned_data['last_name']
        self.instance.user.email = self.cleaned_data['email']
        self.instance.user.save()
        return super(TeamMemberForm, self).save(*args, **kwargs)

teams/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Team
from .forms import TeamForm, TeamMemberForm

# Create your views here.

@login_required
def view(request, team_slug=None):
    team = Team.objects.get(slug=team_slug)
    lunches = team.lunches.all()
    members = team.users.all()
    return render(request, 'teams/view.html', {'lunches': lunches, 'members': members, 'team':team})

@login_required
def create(request):
    form = TeamForm(request.POST or None)
    if form.is_valid():
        team = form.save()
        # Add the current user to the team
        # Since this is the first user, they will automatically be the admin and owner
        team.add_user(request.user)
        return redirect('teams:view', team.slug)
    return render(request, 'teams/create.html', {'form':form})

@login_required
def invite(request, team_slug=None):
    team = Team.objects.get(slug=team_slug)
    form = TeamMemberForm(request.POST or None)
    if form.is_valid():
        user = form.save(team=team)
        return redirect('teams:view', team.slug)
    else:
        print(form.errors)
    return render(request, 'teams/invite.html', {'form':form})

teams/templates/teams/create.html
{% extends "base.html" %}
{% block content %}
    <h1>Welcome {{ user }}</h1>
    <div class="row">
      <div class="col-lg-12 text-left">
        <h2>Build-A-Team</h2>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
      </div>
      </div>
    </div>      
{% endblock %}

teams/templates/teams/invite.html
{% extends "base.html" %}
{% block content %}
    <h1>Welcome {{ user }}</h1>
    <div class="row">
      <div class="col-lg-12 text-left">
        <h2>Add A Member</h2>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
      </div>
      </div>
    </div>      
{% endblock %}

teams/templates/teams/view.html
{% extends "base.html" %}
{% block content %}
    <h1>Team: {{ team.name }}</h1>
    <div class="row">
      <div class="col-lg-6 text-left">
        <h2>Lunches</h2>
        <ul class="list-group">
            {% for lunch in lunches %}
                <li class="list-group-item">{{ lunch }}</a></li>
            {% endfor %}
        </ul>
        <a class="btn btn-primary" href="{% url 'teams:lunches:create' team.slug %}">Create a Lunch</a>
      </div>
      <div class="col-lg-6 text-left">
        <h2>Members</h2>
        <ul class="list-group">
            {% for member in members %}
                <li class="list-group-item">{{ member.first_name }} {{ member.last_name }} ({{ member.email }})</li>
            {% endfor %}
        </ul>
        <a class="btn btn-primary" href="{% url 'teams:invite' team.slug %}">Invite New Member</a>
      </div>
    </div>      
{% endblock %}